services:
  postgres_test:
    image: postgres:16-alpine
    container_name: blablanote-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blablanote_test
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d blablanote_test']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
